version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ./dev.Dockerfile
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`sirkel.in`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
    volumes:
      - ./backend:/go/src/github.com/alkuinvito/backend
    depends_on:
      - reverse-proxy
    command: CompileDaemon -command="./malakh-api"
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`sirkel.in`)"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - reverse-proxy
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass test-redis
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local