version: '3'
services:
  reverse-proxy:
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ./prod.Dockerfile
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`sirkelin.cloud`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
    volumes:
      - ./backend:/go/src/alkuinvito/backend
    depends_on:
      - reverse-proxy
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`sirkelin.cloud`)"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - reverse-proxy
