version: "3.9"
services:
  reverse-proxy:
    restart: always
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  backend:
    restart: unless-stopped
    image: backend
    build:
      context: ./backend
      target: builder
      dockerfile: ./prod.Dockerfile
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`sirkel.in`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
    depends_on: 
      - reverse-proxy
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
  frontend:
    restart: unless-stopped
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./prod.Dockerfile
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`sirkel.in`)"
    depends_on:
      - reverse-proxy