version: "3.9"
services:
  traefik:
    restart: always
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    restart: always
    image: backend
    build:
      context: ./backend
      target: builder
      dockerfile: ./prod.Dockerfile
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${APP_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
    depends_on: 
      - traefik
    command: ./app
  frontend:
    restart: always
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./prod.Dockerfile
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${APP_HOST}`)"
    depends_on:
      - traefik