// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"net/http"
	"sirkelin/backend/app/auth/controller"
	"sirkelin/backend/app/auth/repository"
	"sirkelin/backend/app/auth/service"
	"sirkelin/backend/router"
)

// Injectors from injector.go:

func CreateHTTPServer() *http.Server {
	authRepository := repository.NewAuthRepository()
	authService := service.NewAuthService(authRepository)
	authController := controller.NewAuthController(authService)
	routerRouter := router.NewRouter(authController)
	server := NewServer(routerRouter)
	return server
}

// injector.go:

var authSet = wire.NewSet(repository.NewAuthRepository, wire.Bind(new(repository.IAuthRepository), new(*repository.AuthRepository)), service.NewAuthService, wire.Bind(new(service.IAuthService), new(*service.AuthService)), controller.NewAuthController, wire.Bind(new(controller.IAuthController), new(*controller.AuthController)))
