// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"net/http"
	controller2 "sirkelin/backend/app/room/controller"
	repository2 "sirkelin/backend/app/room/repository"
	service2 "sirkelin/backend/app/room/service"
	"sirkelin/backend/app/user/controller"
	"sirkelin/backend/app/user/repository"
	"sirkelin/backend/app/user/service"
	"sirkelin/backend/app/websocket"
	"sirkelin/backend/initializers"
	"sirkelin/backend/middlewares"
	"sirkelin/backend/router"
)

// Injectors from injector.go:

func CreateHTTPServer() *http.Server {
	userRepository := repository.NewUserRepository()
	db := initializers.NewDB()
	userService := service.NewUserService(userRepository, db)
	roomRepository := repository2.NewRoomRepository()
	roomService := service2.NewRoomService(roomRepository, db)
	middleware := middlewares.NewMiddleware(userService, roomService)
	userController := controller.NewUserController(userService)
	hub := websocket.NewHub()
	roomController := controller2.NewRoomController(userService, roomService, hub)
	routerRouter := router.NewRouter(middleware, userController, roomController, hub)
	server := NewServer(routerRouter)
	return server
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, wire.Bind(new(repository.IUserRepository), new(*repository.UserRepository)), service.NewUserService, wire.Bind(new(service.IUserService), new(*service.UserService)), controller.NewUserController, wire.Bind(new(controller.IUserController), new(*controller.UserController)))

var roomSet = wire.NewSet(repository2.NewRoomRepository, wire.Bind(new(repository2.IRoomRepository), new(*repository2.RoomRepository)), service2.NewRoomService, wire.Bind(new(service2.IRoomService), new(*service2.RoomService)), controller2.NewRoomController, wire.Bind(new(controller2.IRoomController), new(*controller2.RoomController)))
