import Head from 'next/head'
import { useRouter } from 'next/router'
import ErrorPage from 'next/error'
import Link from 'next/link'
import { Montserrat, Yantramanav } from '@next/font/google'
import React, { useState, useContext } from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faComment,
  faHouse,
  faUserGroup,
  faInfinity,
  faArrowRightFromBracket
} from '@fortawesome/free-solid-svg-icons';
import Messages from './messages'
import Circle from './circle'
import { LoginContext } from '@/components/Context'
import Image from 'next/image'
import UserIcon from 'src/asset/follower.png'

const yantramanav = Yantramanav({
  weight: "400",
  subsets: ["latin"]
})

const yBold = Yantramanav({
  weight: "500",
  subsets: ["latin"]
})

const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"]
})

export default function Dashboard() {
  const router = useRouter()
  const { page } = router.query
  const [ view, setView ] = useState(null)
  const [ info, _ ] = useContext(LoginContext)

  React.useEffect(() => {    
    switch(page) {
        case "messages":
          setView(<Messages />)
          break
        case "circle":
          setView(<Circle />)
          break
        default:
          <ErrorPage statusCode={404} /> //TODO: ganti ke error page
          break
      }
    }, [ page ])
  const title = page.charAt(0).toUpperCase() + page.slice(1)

  return (
    <>
      <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className='h-screen'>
          <div className='wh-chat flex'>
            <div className='h-screen flex flex-col navbar-ct backdrop-blur-sm bg-[#323232]/30'>
              <header>
                <h1 className='text-3xl text-center leading-normal translate-y-0.5 grow' style={montserrat.style}>Sirkelin.</h1>
              </header>
              <div className='grow'>
                <navbar className='px-4 grid text-center gap-10 text-xl'>
                  <Link href="/messages" legacyBehavior>
                    <button className='flex group gap-4 hover:bg-gradient-to-r from-violet-900 to-indigo-700 rounded-xl p-3'><FontAwesomeIcon className='self-center group-hover:stroke-white' icon={faComment}/><span style={yantramanav.style} className='ml-4 font-yantramanav'> messages</span></button>
                  </Link>
                  <Link href="/circle" legacyBehavior>
                    <button className='flex group gap-4 hover:bg-gradient-to-r from-violet-900 to-indigo-700 rounded-xl p-3'><FontAwesomeIcon className='self-center group-hover:stroke-white' icon={faInfinity} /><span style={yantramanav.style} className=' ml-3 font-yantramanav'> circle</span></button>
                  </Link>
                  <button className='flex group gap-4 hover:bg-gradient-to-r from-violet-900 to-indigo-700  rounded-xl p-3'><FontAwesomeIcon className='self-center group-hover:stroke-white' icon={faUserGroup} /><span style={yantramanav.style} className=' ml-3 font-yantramanav'> friend list</span></button>
                  <button className='flex group gap-4 hover:bg-gradient-to-r from-violet-900 to-indigo-700  rounded-xl p-3'><FontAwesomeIcon className='self-center group-hover:stroke-white' icon={faHouse} /><span style={yantramanav.style} className=' ml-3 font-yantramanav'> explore</span></button>
                </navbar>
              </div>
              <div className='m-4 p-2 rounded-lg'>
                <div className='flex items-center gap-4'>
                  <Image src={ UserIcon } className='w-10 h-10 '/>
                  <span className='w-full'>
                    <b className='text-lg' style={yBold.style}>{ info.username }</b>
                  </span>
                  <FontAwesomeIcon className='text-lg text-red-800 cursor-pointer' icon={ faArrowRightFromBracket } />
                </div>
              </div>
            </div>
            { view }
          </div>
        </div>
      </main>
    </>
  )
}